services:
  pythondata:
    image: ghcr.io/tyler71/pythondata:latest
    build:
      context: ./build
    labels:
      caddy: ${hostname}
      caddy.reverse_proxy: "{{ upstreams 8888 }}"
    volumes:
      - "./data/stored_files:/home/application/data"
      - "./data/extensions:/usr/local/share/jupyter/lab/extensions"
      - "./data/config:/home/application/.jupyter"
    networks:
      - public
# Bad vim theme needs this command: jt -t onedork -vim

networks:
  public:
    external: true
