name: Build / Upload Docker ghcr.io

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Variables
        id:   v
        run: |
          echo "::set-output name=date::$(date '+%m_%d_%Y')"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Login to personal docker repo
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.PERSONAL_DOCKER_REPO }}
          username: ${{ secrets.PERSONAL_DOCKER_REPO_USER }}
          password: ${{ secrets.PERSONAL_DOCKER_REPO_PASS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: build/
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ steps.v.outputs.date }}
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:build_${{ github.run_number }}
            ${{ secrets.PERSONAL_DOCKER_REPO }}/server/${{ github.event.repository.name }}:${{ steps.v.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
